/// Flutter icons UpdateProfile
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UpdateProfile
///      fonts:
///       - asset: fonts/UpdateProfile.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class UpdateProfile {
  UpdateProfile._();

  static const _kFontFam = 'UpdateProfile';
  static const String _kFontPkg = null;

  static const IconData birthday_cake = IconData(0xf1fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender_alt = IconData(0xf225, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_alt = IconData(0xf3c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campfire = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
